// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnLyZbYtMUrZJnZj_Al7-ENkRRCDtFMZg',
    appId: '1:497490603741:web:acb6ea5221c7d9f0667534',
    messagingSenderId: '497490603741',
    projectId: 'lost-mud',
    authDomain: 'lost-mud.firebaseapp.com',
    storageBucket: 'lost-mud.firebasestorage.app',
    measurementId: 'G-2SR5L4ECB9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHclK3-uvIWTAIU4G5DNBaiS_SOf7D4rk',
    appId: '1:497490603741:android:96499a94b16a1e95667534',
    messagingSenderId: '497490603741',
    projectId: 'lost-mud',
    storageBucket: 'lost-mud.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPB0OPNqC3ti9d34pneJUpwnusXpE1VFc',
    appId: '1:497490603741:ios:d8ac81a02042a9b3667534',
    messagingSenderId: '497490603741',
    projectId: 'lost-mud',
    storageBucket: 'lost-mud.firebasestorage.app',
    iosBundleId: 'com.example.flutterAuthTut',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPB0OPNqC3ti9d34pneJUpwnusXpE1VFc',
    appId: '1:497490603741:ios:d8ac81a02042a9b3667534',
    messagingSenderId: '497490603741',
    projectId: 'lost-mud',
    storageBucket: 'lost-mud.firebasestorage.app',
    iosBundleId: 'com.example.flutterAuthTut',
  );
}
